global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'mysql'
    static_configs:
    - targets: ['localhost:9104']

  - job_name: 'nginx'
    static_configs:
    - targets: ['localhost:9113']

  - job_name: 'php-fpm'
    static_configs:
    - targets: ['localhost:9253']
  
  - job_name: 'node'
    static_configs:
    - targets: ['localhost:9100']
  - job_name: 'blackbox-http_2xx-general'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [http_2xx-general] 
    relabel_configs:
    - source_labels:
      - __address__
      target_label: __param_target
    - source_labels:
      - __param_target
      target_label: instance
    - replacement: localhost:9115
      target_label: __address__
    static_configs:
      - targets:
        - https://cms.arnor.su

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093
